"""Add Geofence and GeofenceEvent models

Revision ID: b1ff0765d64c
Revises: 9ca8930499a9
Create Date: 2025-06-08 01:23:12.432381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ff0765d64c'
down_revision = '9ca8930499a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geofence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geofence_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('geofence_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geofence_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geofence_event_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geofence_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geofence_event_timestamp'))

    op.drop_table('geofence_event')
    op.drop_table('geofence')
    # ### end Alembic commands ###
